### ISSUE TITLE
Fake app

### ISSUE THREAD

**Issue by tauseefrehman2** [Ruban2205/Kwento-Kids-story-app#2]
don't download apk is not oped. and source also removed.

**Comment by Ruban2205** [comment]
I understood your issue. Two years back I have opted this Kwento Application in Google Play store. Few months back Google removed my application because they have updated their policies.

**Comment by Ruban2205** [comment]
> don't download apk is not oped. and source also removed.

I completely acknowledge with your comment. Now, I'm working on the updates to relaunch the application. I'll announce once I will roll-out a new version of Kwento - Kids story application. 

You can check my applications in the given link below. 
https://rubangino.in/projects.html

**Comment by Ruban2205** [comment]
> don't download apk is not oped. and source also removed.

 Dear [Tauseef Rehman](https://github.com/tauseefrehman2),

 I have updated the [Kwento](https://github.com/Ruban2205/Kwento-Kids-story-app) application and it was now accepted and also rolled out by Google Play Services in Google Playstore. 

You can download the application by clicking the below button.

[![Google Playstore](https://img.shields.io/badge/Kwento_on_Google_Play-414141?style=for-the-badge&logo=google-play&logoColor=white)](https://play.google.com/store/apps/details?id=in.rubangino.kwento)

Further issues could be appreciated!

Thanks!
